### ISSUE TITLE
Last known working version combination

### ISSUE THREAD

**Issue by superlukas** [paulcbetts/grunt-build-atom-shell#11]
I've tried a couple of combinations and they all failed. OS X and all tools are up to date. The errors I get vary. They weren't really helpful, but I can paste them anyway if it helps.

What `tag` and `nodeVersion` combination is the latest that you've compiled successfully?

**Comment by paulcbetts** [comment]
v0.20.7 / 0.20.0. Most of these errors are really saying that you can't build Atom Shell on your machine, have you tried building it directly just to see if it works?

**Comment by andymorris** [comment]
I have v0.22.2 / 0.22.0 building without errors on Windows. The last hurdle in my case was that atom-shell's `boostrap.py` (and this grunt task) had to be run with node 0.10 (even though atom-shell itself is far ahead).

However, I'm not 100% clear on what to do next. (I don't do much with Node or Windows, so I'm sure I'm missing some things that are obvious to people who do.) Some things I'm trying to figure out:

1. Is the intended usage to `npm install` my atom-shell app's dependencies, then have `grunt-build-atom-shell` modify `node_modules` in place? If so do I then just copy `node_modules` into `targetDir/resources/app`?
2. It looks like there are a lot of extra build artifacts in `targetDir` (compared to an atom-shell release which is ~1/4 the size) after a successful build. Is there a task/script to clean this up, or docs to know what is needed and what isn't to distribute to end users?

**Comment by paulcbetts** [comment]
You want `0.22.0` for new versions of Atom Shell

**Comment by paulcbetts** [comment]
> Is the intended usage to npm install my atom-shell app's dependencies, then have grunt-build-atom-shell modify node_modules in place?

Yep

> It looks like there are a lot of extra build artifacts in targetDir (compared to an atom-shell release which is ~1/4 the size) after a successful build. Is there a task/script to clean this up, or docs to know what is needed and what isn't to distribute to end users?

That's tough because in atom and atom-shell-starter, it's cleaned up in different ways on different OSs - on Windows for example, we just don't include the files in the installer, whereas on OS X they get explicitly stripped as part of building the .app folder.

**Comment by rishson** [comment]
Hi.
Given the recent renames (atom shell -> electron), switch to iojs and major bumps to this project etc, what is the 'official' latest supported version matrix?

I can successfully build using:

grunt-build-atom-shell: 1.1.5
tag: 0.20.7
nodeVersion: 0.20.0

I cannot get any more recent combinations to work (I get a hang on electron's bootstrap.py)

Ideally, I'd like to be on something like:

grunt-build-atom-shell: 2.0.5
tag: 0.25.0
nodeVersion: ???

Thanks!

**Comment by paulcbetts** [comment]
>  (I get a hang on electron's bootstrap.py)

It's not hanging, it's just taking F O R E V E R downloading a giant file from S3

**Comment by rishson** [comment]
thanks for the quick reply @paulcbetts . I'll leave it running for an hour or so then.
Could you also let me know where to look for the nodeVersion to use against a specific version of electron? I'd like to run against electron 0.25.0 so can I look in the electron src somewhere to find the version of atom/node to use, or are the versions in lockstep now?

**Comment by paulcbetts** [comment]
You probably want nodeVersion 0.25.0 - it seems as if the logic is "0.min.0" (even if you want "0.22.3", nodeVersion is "0.22.0" for example)
