### ISSUE TITLE
Patches on product name and greater visibility

### ISSUE THREAD

**Issue by yrashk** [paulcbetts/grunt-build-atom-shell#12]
First of all, thanks for the project!

I wanted to run a few ideas by you. I've implemented some patches to your tasks to suit our needs and I am wondering if there is any interest in merging any of them:

1. An ability to see stdout/stderr as it happens, often helps with situations like borked download (happens when you're in some parts of South East Asia and forgot to turn the VPN on) or other issues, early on: https://github.com/trustatom-oss/grunt-build-atom-shell/commit/5e4dc685096cf8e55fc870566a275ba9300df496
2. Proper handling of product_name with spaces (Mac apps tend to have that, and ours does): https://github.com/trustatom-oss/grunt-build-atom-shell/commit/9050836b160867b45f22517f7511056e234909ef

Please feel free to cherry-pick or if you want me to do PRs on either of the above, just let me know.

Looking forward to hearing from you.

**Comment by paulcbetts** [comment]
Both of those are great, can you submit PRs for them so you get the sweet sweet Internet Points?

**Comment by yrashk** [comment]
Done.
