### ISSUE TITLE
Same restrictions like building manually?

### ISSUE THREAD

**Issue by Wortex17** [paulcbetts/grunt-build-atom-shell#19]
I was wondering if the same [buidling prerequisites](https://github.com/atom/atom-shell/blob/master/docs/development/build-instructions-windows.md) are given, especially regarding the *installed* nodejs (/iojs) version (requiring a global node 0.10.x), when using this grunt task. If yes, what exactly is the node version field for?

**Comment by paulcbetts** [comment]
Yes, those build prerequisites are the same. The nodeVersion field is hard to explain, just follow the instructions and you will be :gem:
