### ISSUE TITLE
Fail on Windows

### ISSUE THREAD

**Issue by Trixt0r** [paulcbetts/grunt-build-atom-shell#25]
I get the following output if i run the task on Windows (10 x64 technical preview):

>> Running: python script/bootstrap.py
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 127, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 34, in main
>>     update_atom_shell()
>>   File "script/bootstrap.py", line 123, in update_atom_shell
>>     execute_stdout([sys.executable, update])
>>   File "D:\dropclient\build\win32\atom_shell_build\atom-shell\script\lib\util.py", line 150, in execute_stdout
>>     execute(argv)
>>   File "D:\dropclient\build\win32\atom_shell_build\atom-shell\script\lib\util.py", line 138, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['D:\\Python\\python.exe', 'D:\\dropclient\\build\\win32\\atom_shell_build\\atom-shell\\script\\update.py']' returned non-zero exit status 1

Python version is 2.7.9.
The node version, I run it with, is 0.10.35 32bit. I change the version with nvm in a previous grunt task.
However, the node version, I start grunt with, is 0.12.0.
If I just run `python script\bootstrap.py` it works without any issues.

Someone any suggestions?

-Trixt0r

**Comment by Trixt0r** [comment]
Okay, I now figured out that there is a problem with long strings in the *.exe name.
I had a name with a hash in it, something like `app-prd-FHZDH-UZRE8670-98867HFG-JFZDN-HUZFG`.

Anyway, shortening the name, solved the problem.

But I think it is still an issue which has to be fixed, since there is no such problem on OS X.

I guess this is a Python on Windows problem.

-Trixt0r

**Comment by paulcbetts** [comment]
Can't really fix this, sorry :(
