### ISSUE TITLE
Can I get an overview of this task's whole process

### ISSUE THREAD

**Issue by maxkorp** [paulcbetts/grunt-build-atom-shell#28]
Having issues with the plugin (cross platform, some of the same issues, some different). Trying to figure out exactly whats going on. I think I have an understanding of how things happen, but I'm not sure. Trying to go through these steps manually yields some odd issues. I could use a bit of explaination to how things are working. Read up on rx.js a bit, but I'm still missing something I think. Assuming productname is product and projectname is project, config is Release

  1. clone atom-shell
  2. modify atom.gyp
  3. BOOTSTRAP: 

    ```bash
    GYP_DEFINES={stuff} ./script/bootstrap.py -v
    ```
  4. BUILD 

    ```bash
    ./script/build.py -c Release -t project
    ```
  5. INSTALL CUSTOM  NODE

    ```bash
    GYP_DEFINES={stuff} nodegyp install --target={node-version} --arch={arch} --dist-url={ghcontractor.blablabla}
    ``` 
  6. NODELIB 

    ```bash
    ./script/build.py -c Release -t generate_node_lib
    ```
    then copy `./out/Release/node.lib` back to `~/.project/.node-gyp/{version}/node.lib
    note, this fails for me:

    ```bash
    ninja: Entering directory `out/Release'
    ninja: error: unknown target 'generate_node_lib'
    ```
  7. REBUILD NATIVE MODULES
    
    ```bash
    HOME=npm rebuild --target={node-version} --arch={arch}
    ```

am I missing something? I'm perhaps most confused by the issue generating node lib. Cant find reference to that anywhere in the atom-shell code or atom/node code, except for one place. Did that command change? Note I am building 0.22.3, on OSX yosemite.

I know I've seen it referenced in the issue that spawned this task, but when I go to the line thats referenced in atom-gyp, it doesnt line up anymore.

**Comment by paulcbetts** [comment]
generate_node_lib should only run on Windows (it only exists on Windows). How are you invoking the task?

**Comment by maxkorp** [comment]
Ah interesting, that's windows only. Good to know!

The task is being invoked by just `grunt build-atom-shell`. We get inconsistant errors though during builds. Not sure exactly what the issue is, but I'm just trying to follow the path the plugin takes so I can try to diagnose things and figure out what's at the root of it all.

**Comment by paulcbetts** [comment]
Can you give a few examples of output of `grunt build-atom-shell --verbose --stack`?

**Comment by maxkorp** [comment]
Apparently it's magically started working for me, no issues now >.<

I'm out of office from the other guys atm, so I'll ask them to try again. If the contents of my ~/.myproject/.node-gyp folder were screwed up somehow, could that prevent proper rebuilds from happening?

**Comment by paulcbetts** [comment]
>  If the contents of my ~/.myproject/.node-gyp folder were screwed up somehow, could that prevent proper rebuilds from happening?

Who knows? Impossible to say really, when it comes to node.js

> As an aside, if I'm getting module version mismatches, I'm assuming thats something to do with the nodeVersion not matching up. I've got atom-shell targeting 0.22.3, and nodeVersion set to 0.22.0. 

Yep and yep. Something's going odd.

**Comment by maxkorp** [comment]
Hrm, so setting nodeVersion to 0.22.3 (matching atom-shell, just minus the v at the beginning (from the tag) fixes it.

**Comment by maxkorp** [comment]
@paulcbetts OK, so it _does_ have issues in windows apparently (potentially). It's not verbose stack, but heres the basic error in windows. 
```
Running "build-atom-shell" task
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['D:\\Projects\\MyProject\\vendor\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['D:\\Projects\\MyProject\\vendor\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1
Warning: null Use --force to continue.

Aborted due to warnings.
```

**Comment by maxkorp** [comment]
Got the verbose output.
```
Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Cloning to D:\Projects\MyProject\vendor
>> Running: git clone https://github.com/atom/atom-shell
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.22.3
>> Rigging atom.gyp to have correct name
Reading D:\Projects\MyProject\vendor\atom-shell\atom.gyp...OK
Writing D:\Projects\MyProject\vendor\atom-shell\atom.gyp...OK
>> Running: python script/bootstrap.py
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['D:\\Projects\\MyProject\\vendor\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1
>> Rigging atom.gyp to have correct name
Reading D:\Projects\MyProject\vendor\atom-shell\atom.gyp...OK
Writing D:\Projects\MyProject\vendor\atom-shell\atom.gyp...OK
>> Running: python script/bootstrap.py
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "D:\Projects\MyProject\vendor\atom-shell\script\lib\util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['D:\\Projects\\MyProject\\vendor\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1
Warning: null Use --force to continue.
Error: null
    at ChildProcess.<anonymous> (D:\Projects\MyProject\node_modules\grunt-build-atom-shell\tasks\task-helpers.coffee:93:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

Aborted due to warnings.
```

**Comment by maxkorp** [comment]
Figured it out! Pretty sure it was lack of an --msvs_version flag when bootstrap.py calls apm install. Completely outside the scope of this project :+1: Thanks so much for all of your help man.
