### ISSUE TITLE
2.0.3 not on NPM

### ISSUE THREAD

**Issue by maxkorp** [paulcbetts/grunt-build-atom-shell#31]
2.0.3 isnt on NPM (although a 2.0.4 would be welcome, after #30, since I'm already being a hassling beggar). Trying to bump up to electron 0.24.0, and need that fix in 2.0.3. Running it off github atm, but just thought I'd point it out.

**Comment by paulcbetts** [comment]
2.0.4 should be on npm now, it also fixes a bug with building Linux

**Comment by maxkorp** [comment]
:+1: thanks dude!
