### ISSUE TITLE
*.asar

### ISSUE THREAD

**Issue by wormen** [paulcbetts/grunt-build-atom-shell#34]
tell me how to package an application using * .asar

**Comment by paulcbetts** [comment]
https://github.com/atom/electron-starter/blob/master/build/tasks/generate-asar.coffee should get you most of the way

**Comment by wormen** [comment]
No, I'm not talking about that ... I'm about ready application where vpesto directory used * .asar

as an example
```
electron/resources/
└── app.asar
```

**Comment by paulcbetts** [comment]
Yep! That looks good
